---
title: "Transcript of Colin Powell\'s Presentation to the United Nations Security Council, Feb. 5 2003"
layout: post
tp_urlid: "6a010534988cd3970b0120a5b361dd970c"
tp_favoritecount: 0
tp_commentcount: 0
tp_permalink: "http://www.monkinetic.com/2003/02/transcript-of-colin-powells-presentation-to-the-united-nations-security-council-feb-5-2003.html"
---
<script language="JavaScript" type="text/javascript">
&lt;!--// hide from older browsers
		var g_hilitedObject;
		function getStyleObject( id )
		{
			if ( document.all )
			{
				return document.all[ id ].style;
			}
			else
			{
				return document.getElementById( id ).style;
			}
			return false;
		}
		
		function setHilite( id )
		{
			if ( ! id )
			{
				id = window.location.hash.substring( 1 );
			}
			
			if ( id )
			{
				if ( id.substring(0,1) == &#39;p&#39; )
				{
					// id and name share the same space, so we prepended &#39;m&#39; to the id&#39;s in the html
					id = &#39;m&#39; + id; 
				}
				if ( g_hilitedObject )
				{
					g_hilitedObject.backgroundColor = &#39;&#39;;
				}
				g_hilitedObject = getStyleObject( id );
				if ( g_hilitedObject )
				{
					g_hilitedObject.backgroundColor = &#39;#CCCCCC&#39;;
					window.setTimeout( &#39;setHilite()&#39;, 1000 );	
					return
				}
			}
			window.setTimeout( &#39;setHilite()&#39;, 1000 );
			return;
		}
		window.setTimeout( &#39;setHilite()&#39;, 1000 );
// end hiding--&gt;
</script>
(Text is from CNN&#39;s <a href="http://www.cnn.com/2003/US/02/05/sprj.irq.powell.transcript/index.html">transcript</a>.)

<p>
<a name="p0"></a></p><p id="mp0">Following is a transcript of U.S. Secretary of State Colin Powell&#39;s presentation to the U.N. Security Council on the U.S. case against Iraq. <a href="#p0">#</a></p>
<div id="h0"><h2>Part 1: Introduction <a href="#h0" name="h0">#</a></h2>
<a name="p1"></a><p id="mp1">Thank you, Mr. President. <a href="#p1">#</a></p>
<a name="p2"></a><p id="mp2">Mr. President, Mr. Secretary General, distinguished colleagues, I would like to begin by expressing my thanks for the special effort that each of you made to be here today. <a href="#p2">#</a></p>
<a name="p3"></a><p id="mp3">This is important day for us all as we review the situation with respect to Iraq and its disarmament obligations under U.N. Security Council Resolution 1441. <a href="#p3">#</a></p>
<a name="p4"></a><p id="mp4">Last November 8, this council passed Resolution 1441 by a unanimous vote. The purpose of that resolution was to disarm Iraq of its weapons of mass destruction. Iraq had already been found guilty of material breach of its obligations, stretching back over 16 previous resolutions and 12 years. <a href="#p4">#</a></p>

<a name="p5"></a><p id="mp5">Resolution 1441 was not dealing with an innocent party, but a regime this council has repeatedly convicted over the years. Resolution 1441 gave Iraq one last chance, one last chance to come into compliance or to face serious consequences. No council member present in voting on that day had any illusions about the nature and intent of the resolution or what serious consequences meant if Iraq did not comply. <a href="#p5">#</a></p>
<a name="p6"></a><p id="mp6">And to assist in its disarmament, we called on Iraq to cooperate with returning inspectors from UNMOVIC and IAEA. <a href="#p6">#</a></p>
<a name="p7"></a><p id="mp7">We laid down tough standards for Iraq to meet to allow the inspectors to do their job. <a href="#p7">#</a></p>
<a name="p8"></a><p id="mp8">This council placed the burden on Iraq to comply and disarm and not on the inspectors to find that which Iraq has gone out of its way to conceal for so long. Inspectors are inspectors; they are not detectives. <a href="#p8">#</a></p>
<a name="p9"></a><p id="mp9">I asked for this session today for two purposes: First, to support the core assessments made by Dr. Blix and Dr. ElBaradei. As Dr. Blix reported to this council on January 27th, &quot;Iraq appears not to have come to a genuine acceptance, not even today, of the disarmament which was demanded of it.&quot; <a href="#p9">#</a></p>
<a name="p10"></a><p id="mp10">And as Dr. ElBaradei reported, Iraq&#39;s declaration of December 7, &quot;did not provide any new information relevant to certain questions that have been outstanding since 1998.&quot; <a href="#p10">#</a></p>

<a name="p11"></a><p id="mp11">My second purpose today is to provide you with additional information, to share with you what the United States knows about Iraq&#39;s weapons of mass destruction as well as Iraq&#39;s involvement in terrorism, which is also the subject of Resolution 1441 and other earlier resolutions. <a href="#p11">#</a></p>
<a name="p12"></a><p id="mp12">I might add at this point that we are providing all relevant information we can to the inspection teams for them to do their work. <a href="#p12">#</a></p>
<a name="p13"></a><p id="mp13">The material I will present to you comes from a variety of sources. Some are U.S. sources. And some are those of other countries. Some of the sources are technical, such as intercepted telephone conversations and photos taken by satellites. Other sources are people who have risked their lives to let the world know what Saddam Hussein is really up to. <a href="#p13">#</a></p>
<a name="p14"></a><p id="mp14">I cannot tell you everything that we know. But what I can share with you, when combined with what all of us have learned over the years, is deeply troubling. <a href="#p14">#</a></p>
<a name="p15"></a><p id="mp15">What you will see is an accumulation of facts and disturbing patterns of behavior. The facts on Iraq&#39;s behavior demonstrate that Saddam Hussein and his regime have made no effort -- no effort -- to disarm as required by the international community. <a href="#p15">#</a></p>
<a name="p16"></a><p id="mp16">Indeed, the facts and Iraq&#39;s behavior show that Saddam Hussein and his regime are concealing their efforts to produce more weapons of mass destruction. <a href="#p16">#</a></p></div>

<div id="h1"><h2>Part 2: Hiding prohibited equipment <a href="#h1" name="h1">#</a></h2>
<a name="p17"></a><p id="mp17">Let me begin by playing a tape for you. What you&#39;re about to hear is a conversation that my government monitored. It takes place on November 26 of last year, on the day before United Nations teams resumed inspections in Iraq. <a href="#p17">#</a></p>
<a name="p18"></a><p id="mp18">The conversation involves two senior officers, a colonel and a brigadier general, from Iraq&#39;s elite military unit, the Republican Guard. <a href="#p18">#</a></p>
<a name="p19"></a><p id="mp19">[Following is a U.S. translation of that taped conversation.] <a href="#p19">#</a></p>
<a name="p20"></a><p id="mp20">GEN: Yeah. <a href="#p20">#</a></p>
<a name="p21"></a><p id="mp21">COL: About this committee that is coming... <a href="#p21">#</a></p>

<a name="p22"></a><p id="mp22">GEN: Yeah, yeah. <a href="#p22">#</a></p>
<a name="p23"></a><p id="mp23">COL: ...with Mohamed ElBaradei [Director, International Atomic Energy Agency] <a href="#p23">#</a></p>
<a name="p24"></a><p id="mp24">GEN: Yeah, yeah. <a href="#p24">#</a></p>
<a name="p25"></a><p id="mp25">COL: Yeah. <a href="#p25">#</a></p>
<a name="p26"></a><p id="mp26">GEN: Yeah? <a href="#p26">#</a></p>
<a name="p27"></a><p id="mp27">COL: We have this modified vehicle. <a href="#p27">#</a></p>

<a name="p28"></a><p id="mp28">GEN: Yeah. <a href="#p28">#</a></p>
<a name="p29"></a><p id="mp29">COL: What do we say if one of them sees it? <a href="#p29">#</a></p>
<a name="p30"></a><p id="mp30">GEN: You didn&#39;t get a modified... You don&#39;t have a modified... <a href="#p30">#</a></p>
<a name="p31"></a><p id="mp31">COL: By God, I have one. <a href="#p31">#</a></p>
<a name="p32"></a><p id="mp32">GEN: Which? From the workshop...? <a href="#p32">#</a></p>
<a name="p33"></a><p id="mp33">COL: From the al-Kindi Company <a href="#p33">#</a></p>

<a name="p34"></a><p id="mp34">GEN: What? <a href="#p34">#</a></p>
<a name="p35"></a><p id="mp35">COL: From al-Kindi. <a href="#p35">#</a></p>
<a name="p36"></a><p id="mp36">GEN: Yeah, yeah. I&#39;ll come to you in the morning. I have some comments. I&#39;m worried you all have something left. <a href="#p36">#</a></p>
<a name="p37"></a><p id="mp37">COL: We evacuated everything. We don&#39;t have anything left. <a href="#p37">#</a></p>
<a name="p38"></a><p id="mp38">GEN: I will come to you tomorrow. <a href="#p38">#</a></p>
<a name="p39"></a><p id="mp39">COL: Okay. <a href="#p39">#</a></p>

<a name="p40"></a><p id="mp40">GEN: I have a conference at Headquarters, before I attend the conference I will come to you. <a href="#p40">#</a></p>
<a name="p41"></a><p id="mp41">Let me pause and review some of the key elements of this conversation that you just heard between these two officers. <a href="#p41">#</a></p>
<a name="p42"></a><p id="mp42">First, they acknowledge that our colleague, Mohamed ElBaradei, is coming, and they know what he&#39;s coming for, and they know he&#39;s coming the next day. He&#39;s coming to look for things that are prohibited. He is expecting these gentlemen to cooperate with him and not hide things. <a href="#p42">#</a></p>
<a name="p43"></a><p id="mp43">But they&#39;re worried. &quot;We have this modified vehicle. What do we say if one of them sees it?&quot; <a href="#p43">#</a></p>
<a name="p44"></a><p id="mp44">What is their concern? Their concern is that it&#39;s something they should not have, something that should not be seen. <a href="#p44">#</a></p>
<a name="p45"></a><p id="mp45">The general is incredulous: &quot;You didn&#39;t get a modified. You don&#39;t have one of those, do you?&quot; <a href="#p45">#</a></p>

<a name="p46"></a><p id="mp46">&quot;I have one.&quot; <a href="#p46">#</a></p>
<a name="p47"></a><p id="mp47">&quot;Which, from where?&quot; <a href="#p47">#</a></p>
<a name="p48"></a><p id="mp48">&quot;From the workshop, from the al-Kindi Company?&quot; <a href="#p48">#</a></p>
<a name="p49"></a><p id="mp49">&quot;What?&quot; <a href="#p49">#</a></p>
<a name="p50"></a><p id="mp50">&quot;From al-Kindi.&quot; <a href="#p50">#</a></p>
<a name="p51"></a><p id="mp51">&quot;I&#39;ll come to see you in the morning. I&#39;m worried. You all have something left.&quot; <a href="#p51">#</a></p>

<a name="p52"></a><p id="mp52">&quot;We evacuated everything. We don&#39;t have anything left.&quot; <a href="#p52">#</a></p>
<a name="p53"></a><p id="mp53">Note what he says: &quot;We evacuated everything.&quot; <a href="#p53">#</a></p>
<a name="p54"></a><p id="mp54">We didn&#39;t destroy it. We didn&#39;t line it up for inspection. We didn&#39;t turn it into the inspectors. We evacuated it to make sure it was not around when the inspectors showed up. <a href="#p54">#</a></p>
<a name="p55"></a><p id="mp55">&quot;I will come to you tomorrow.&quot; <a href="#p55">#</a></p>
<a name="p56"></a><p id="mp56">The al-Kindi Company: This is a company that is well known to have been involved in prohibited weapons systems activity. <a href="#p56">#</a></p>
<a name="p57"></a><p id="mp57">Let me play another tape for you. As you will recall, the inspectors found 12 empty chemical warheads on January 16. On January 20, four days later, Iraq promised the inspectors it would search for more. You will now hear an officer from Republican Guard headquarters issuing an instruction to an officer in the field. Their conversation took place just last week on January 30. <a href="#p57">#</a></p>

<a name="p58"></a><p id="mp58">Let me pause again and review the elements of this message. <a href="#p58">#</a></p>
<a name="p59"></a><p id="mp59">&quot;They&#39;re inspecting the ammunition you have, yes.&quot; <a href="#p59">#</a></p>
<a name="p60"></a><p id="mp60">&quot;Yes.&quot; <a href="#p60">#</a></p>
<a name="p61"></a><p id="mp61">&quot;For the possibility there are forbidden ammo.&quot; <a href="#p61">#</a></p>
<a name="p62"></a><p id="mp62">&quot;For the possibility there is by chance forbidden ammo?&quot; <a href="#p62">#</a></p>
<a name="p63"></a><p id="mp63">&quot;Yes.&quot; <a href="#p63">#</a></p>

<a name="p64"></a><p id="mp64">&quot;And we sent you a message yesterday to clean out all of the areas, the scrap areas, the abandoned areas. Make sure there is nothing there.&quot; <a href="#p64">#</a></p>
<a name="p65"></a><p id="mp65">Remember the first message, evacuated. <a href="#p65">#</a></p>
<a name="p66"></a><p id="mp66">This is all part of a system of hiding things and moving things out of the way and making sure they have left nothing behind. <a href="#p66">#</a></p>
<a name="p67"></a><p id="mp67">If you go a little further into this message, and you see the specific instructions from headquarters: &quot;After you have carried out what is contained in this message, destroy the message because I don&#39;t want anyone to see this message.&quot; <a href="#p67">#</a></p>
<a name="p68"></a><p id="mp68">&quot;OK, OK.&quot; <a href="#p68">#</a></p>
<a name="p69"></a><p id="mp69">Why? Why? <a href="#p69">#</a></p>

<a name="p70"></a><p id="mp70">This message would have verified to the inspectors that they have been trying to turn over things. They were looking for things. But they don&#39;t want that message seen, because they were trying to clean up the area to leave no evidence behind of the presence of weapons of mass destruction. And they can claim that nothing was there. And the inspectors can look all they want, and they will find nothing. <a href="#p70">#</a></p>
<a name="p71"></a><p id="mp71">This effort to hide things from the inspectors is not one or two isolated events, quite the contrary. This is part and parcel of a policy of evasion and deception that goes back 12 years, a policy set at the highest levels of the Iraqi regime.  <a href="#p71">#</a></p></div>
<div id="h2"><h2>Part 3: Attempt to thwart inspection <a href="#h2" name="h2">#</a></h2>
<a name="p72"></a><p id="mp72">We know that Saddam Hussein has what is called &quot;a higher committee for monitoring the inspections teams.&quot; Think about that. Iraq has a high-level committee to monitor the inspectors who were sent in to monitor Iraq&#39;s disarmament. <a href="#p72">#</a></p>
<a name="p73"></a><p id="mp73">Not to cooperate with them, not to assist them, but to spy on them and keep them from doing their jobs. <a href="#p73">#</a></p>
<a name="p74"></a><p id="mp74">The committee reports directly to Saddam Hussein. It is headed by Iraq&#39;s vice president, Taha Yassin Ramadan. Its members include Saddam Hussein&#39;s son Qusay. <a href="#p74">#</a></p>

<a name="p75"></a><p id="mp75">This committee also includes Lt. Gen. Amir al-Saadi, an adviser to Saddam. In case that name isn&#39;t immediately familiar to you, Gen. Saadi has been the Iraqi regime&#39;s primary point of contact for Dr. Blix and Dr. ElBaradei. It was Gen. Saadi who last fall publicly pledged that Iraq was prepared to cooperate unconditionally with inspectors. Quite the contrary, Saadi&#39;s job is not to cooperate, it is to deceive; not to disarm, but to undermine the inspectors; not to support them, but to frustrate them and to make sure they learn nothing. <a href="#p75">#</a></p>
<a name="p76"></a><p id="mp76">We have learned a lot about the work of this special committee. We learned that just prior to the return of inspectors last November the regime had decided to resume what we heard called, &quot;the old game of cat and mouse.&quot; <a href="#p76">#</a></p>
<a name="p77"></a><p id="mp77">For example, let me focus on the now famous declaration that Iraq submitted to this council on December 7. Iraq never had any intention of complying with this council&#39;s mandate. <a href="#p77">#</a></p>
<a name="p78"></a><p id="mp78">Instead, Iraq planned to use the declaration, overwhelm us and to overwhelm the inspectors with useless information about Iraq&#39;s permitted weapons so that we would not have time to pursue Iraq&#39;s prohibited weapons. Iraq&#39;s goal was to give us, in this room, to give those of us on this council the false impression that the inspection process was working. <a href="#p78">#</a></p>
<a name="p79"></a><p id="mp79">You saw the result. Dr. Blix pronounced the 12,200-page declaration, rich in volume, but poor in information and practically devoid of new evidence. <a href="#p79">#</a></p>
<a name="p80"></a><p id="mp80">Could any member of this council honestly rise in defense of this false declaration? <a href="#p80">#</a></p>

<a name="p81"></a><p id="mp81">Everything we have seen and heard indicates that, instead of cooperating actively with the inspectors to ensure the success of their mission, Saddam Hussein and his regime are busy doing all they possibly can to ensure that inspectors succeed in finding absolutely nothing. <a href="#p81">#</a></p>
<a name="p82"></a><p id="mp82">My colleagues, every statement I make today is backed up by sources, solid sources. These are not assertions. What we&#39;re giving you are facts and conclusions based on solid intelligence. I will cite some examples, and these are from human sources. <a href="#p82">#</a></p>
<a name="p83"></a><p id="mp83">Orders were issued to Iraq&#39;s security organizations, as well as to Saddam Hussein&#39;s own office, to hide all correspondence with the Organization of Military Industrialization. <a href="#p83">#</a></p>
<a name="p84"></a><p id="mp84">This is the organization that oversees Iraq&#39;s weapons of mass destruction activities. Make sure there are no documents left which could connect you to the OMI. <a href="#p84">#</a></p>
<a name="p85"></a><p id="mp85">We know that Saddam&#39;s son, Qusay, ordered the removal of all prohibited weapons from Saddam&#39;s numerous palace complexes. We know that Iraqi government officials, members of the ruling Baath Party and scientists have hidden prohibited items in their homes. Other key files from military and scientific establishments have been placed in cars that are being driven around the countryside by Iraqi intelligence agents to avoid detection. <a href="#p85">#</a></p>
<a name="p86"></a><p id="mp86">Thanks to intelligence they were provided, the inspectors recently found dramatic confirmation of these reports. When they searched the home of an Iraqi nuclear scientist, they uncovered roughly 2,000 pages of documents. You see them here being brought out of the home and placed in U.N. hands. Some of the material is classified and related to Iraq&#39;s nuclear program. <a href="#p86">#</a></p>

<a name="p87"></a><p id="mp87">Tell me, answer me, are the inspectors to search the house of every government official, every Baath Party member and every scientist in the country to find the truth, to get the information they need, to satisfy the demands of our council? <a href="#p87">#</a></p>
<a name="p88"></a><p id="mp88">Our sources tell us that, in some cases, the hard drives of computers at Iraqi weapons facilities were replaced. Who took the hard drives. Where did they go? What&#39;s being hidden? Why? There&#39;s only one answer to the why: to deceive, to hide, to keep from the inspectors. <a href="#p88">#</a></p>
<a name="p89"></a><p id="mp89">Numerous human sources tell us that the Iraqis are moving, not just documents and hard drives, but weapons of mass destruction to keep them from being found by inspectors. <a href="#p89">#</a></p>
<a name="p90"></a><p id="mp90">While we were here in this council chamber debating Resolution 1441 last fall, we know, we know from sources that a missile brigade outside Baghdad was disbursing rocket launchers and warheads containing biological warfare agents to various locations, distributing them to various locations in western Iraq. Most of the launchers and warheads have been hidden in large groves of palm trees and were to be moved every one to four weeks to escape detection. <a href="#p90">#</a></p>
<a name="p91"></a><p id="mp91">We also have satellite photos that indicate that banned materials have recently been moved from a number of Iraqi weapons of mass destruction facilities. <a href="#p91">#</a></p>
<a name="p92"></a><p id="mp92">Let me say a word about satellite images before I show a couple. The photos that I am about to show you are sometimes hard for the average person to interpret, hard for me. The painstaking work of photo analysis takes experts with years and years of experience, pouring for hours and hours over light tables. But as I show you these images, I will try to capture and explain what they mean, what they indicate to our imagery specialists. <a href="#p92">#</a></p>

<a name="p93"></a><p id="mp93">Let&#39;s look at one. This one is about a weapons munition facility, a facility that holds ammunition at a place called Taji (ph). This is one of about 65 such facilities in Iraq. We know that this one has housed chemical munitions. In fact, this is where the Iraqis recently came up with the additional four chemical weapon shells. <a href="#p93">#</a></p>
<a name="p94"></a><p id="mp94">Here, you see 15 munitions bunkers in yellow and red outlines. The four that are in red squares represent active chemical munitions bunkers. <a href="#p94">#</a></p>
<a name="p95"></a><p id="mp95">How do I know that? How can I say that? Let me give you a closer look. Look at the image on the left. On the left is a close-up of one of the four chemical bunkers. The two arrows indicate the presence of sure signs that the bunkers are storing chemical munitions. The arrow at the top that says security points to a facility that is the signature item for this kind of bunker. Inside that facility are special guards and special equipment to monitor any leakage that might come out of the bunker. <a href="#p95">#</a></p>
<a name="p96"></a><p id="mp96">The truck you also see is a signature item. It&#39;s a decontamination vehicle in case something goes wrong. <a href="#p96">#</a></p>
<a name="p97"></a><p id="mp97">This is characteristic of those four bunkers. The special security facility and the decontamination vehicle will be in the area, if not at any one of them or one of the other, it is moving around those four, and it moves as it needed to move, as people are working in the different bunkers. <a href="#p97">#</a></p>
<a name="p98"></a><p id="mp98">Now look at the picture on the right. You are now looking at two of those sanitized bunkers. The signature vehicles are gone, the tents are gone, it&#39;s been cleaned up, and it was done on the 22nd of December, as the U.N. inspection team is arriving, and you can see the inspection vehicles arriving in the lower portion of the picture on the right. <a href="#p98">#</a></p>

<a name="p99"></a><p id="mp99">The bunkers are clean when the inspectors get there. They found nothing. <a href="#p99">#</a></p>
<a name="p100"></a><p id="mp100">This sequence of events raises the worrisome suspicion that Iraq had been tipped off to the forthcoming inspections at Taji (ph). As it did throughout the 1990s, we know that Iraq today is actively using its considerable intelligence capabilities to hide its illicit activities. From our sources, we know that inspectors are under constant surveillance by an army of Iraqi intelligence operatives. <a href="#p100">#</a></p>
<a name="p101"></a><p id="mp101">Iraq is relentlessly attempting to tap all of their communications, both voice and electronics. <a href="#p101">#</a></p>
<a name="p102"></a><p id="mp102">I would call my colleagues attention to the fine paper that United Kingdom distributed yesterday, which describes in exquisite detail Iraqi deception activities. <a href="#p102">#</a></p>
<a name="p103"></a><p id="mp103">In this next example, you will see the type of concealment activity Iraq has undertaken in response to the resumption of inspections. Indeed, in November 2002, just when the inspections were about to resume this type of activity spiked. Here are three examples. <a href="#p103">#</a></p>
<a name="p104"></a><p id="mp104">At this ballistic missile site, on November 10, we saw a cargo truck preparing to move ballistic missile components. At this biological weapons related facility, on November 25, just two days before inspections resumed, this truck caravan appeared, something we almost never see at this facility, and we monitor it carefully and regularly. <a href="#p104">#</a></p>

<a name="p105"></a><p id="mp105">At this ballistic missile facility, again, two days before inspections began, five large cargo trucks appeared along with the truck-mounted crane to move missiles. We saw this kind of house cleaning at close to 30 sites. <a href="#p105">#</a></p>
<a name="p106"></a><p id="mp106">Days after this activity, the vehicles and the equipment that I&#39;ve just highlighted disappear and the site returns to patterns of normalcy. We don&#39;t know precisely what Iraq was moving, but the inspectors already knew about these sites, so Iraq knew that they would be coming. <a href="#p106">#</a></p>
<a name="p107"></a><p id="mp107">We must ask ourselves: Why would Iraq suddenly move equipment of this nature before inspections if they were anxious to demonstrate what they had or did not have? <a href="#p107">#</a></p>
<a name="p108"></a><p id="mp108">Remember the first intercept in which two Iraqis talked about the need to hide a modified vehicle from the inspectors. Where did Iraq take all of this equipment? Why wasn&#39;t it presented to the inspectors? <a href="#p108">#</a></p>
<a name="p109"></a><p id="mp109">Iraq also has refused to permit any U-2 reconnaissance flights that would give the inspectors a better sense of what&#39;s being moved before, during and after inspectors. <a href="#p109">#</a></p>
<a name="p110"></a><p id="mp110">This refusal to allow this kind of reconnaissance is in direct, specific violation of operative paragraph seven of our Resolution 1441. <a href="#p110">#</a></p>

<a name="p111"></a><p id="mp111">Saddam Hussein and his regime are not just trying to conceal weapons, they&#39;re also trying to hide people. You know the basic facts. Iraq has not complied with its obligation to allow immediate, unimpeded, unrestricted and private access to all officials and other persons as required by Resolution 1441.  <a href="#p111">#</a></p></div>
<div id="h3"><h2>Part 4: Access to scientists <a href="#h3" name="h3">#</a></h2>
<a name="p112"></a><p id="mp112">The regime only allows interviews with inspectors in the presence of an Iraqi official, a minder. The official Iraqi organization charged with facilitating inspections announced, announced publicly and announced ominously that, quote, &quot;Nobody is ready to leave Iraq to be interviewed.&quot; <a href="#p112">#</a></p>
<a name="p113"></a><p id="mp113">Iraqi Vice President Ramadan accused the inspectors of conducting espionage, a veiled threat that anyone cooperating with U.N. inspectors was committing treason. <a href="#p113">#</a></p>
<a name="p114"></a><p id="mp114">Iraq did not meet its obligations under 1441 to provide a comprehensive list of scientists associated with its weapons of mass destruction programs. Iraq&#39;s list was out of date and contained only about 500 names, despite the fact that UNSCOM had earlier put together a list of about 3,500 names. <a href="#p114">#</a></p>
<a name="p115"></a><p id="mp115">Let me just tell you what a number of human sources have told us. <a href="#p115">#</a></p>

<a name="p116"></a><p id="mp116">Saddam Hussein has directly participated in the effort to prevent interviews. In early December, Saddam Hussein had all Iraqi scientists warned of the serious consequences that they and their families would face if they revealed any sensitive information to the inspectors. They were forced to sign documents acknowledging that divulging information is punishable by death. <a href="#p116">#</a></p>
<a name="p117"></a><p id="mp117">Saddam Hussein also said that scientists should be told not to agree to leave Iraq; anyone who agreed to be interviewed outside Iraq would be treated as a spy. This violates 1441. <a href="#p117">#</a></p>
<a name="p118"></a><p id="mp118">In mid-November, just before the inspectors returned, Iraqi experts were ordered to report to the headquarters of the special security organization to receive counterintelligence training. The training focused on evasion methods, interrogation resistance techniques, and how to mislead inspectors. <a href="#p118">#</a></p>
<a name="p119"></a><p id="mp119">Ladies and gentlemen, these are not assertions. These are facts, corroborated by many sources, some of them sources of the intelligence services of other countries. <a href="#p119">#</a></p>
<a name="p120"></a><p id="mp120">For example, in mid-December weapons experts at one facility were replaced by Iraqi intelligence agents who were to deceive inspectors about the work that was being done there. <a href="#p120">#</a></p>
<a name="p121"></a><p id="mp121">On orders from Saddam Hussein, Iraqi officials issued a false death certificate for one scientist, and he was sent into hiding. <a href="#p121">#</a></p>

<a name="p122"></a><p id="mp122">In the middle of January, experts at one facility that was related to weapons of mass destruction, those experts had been ordered to stay home from work to avoid the inspectors. Workers from other Iraqi military facilities not engaged in illicit weapons projects were to replace the workers who&#39;d been sent home. A dozen experts have been placed under house arrest, not in their own houses, but as a group at one of Saddam Hussein&#39;s guest houses. It goes on and on and on. <a href="#p122">#</a></p>
<a name="p123"></a><p id="mp123">As the examples I have just presented show, the information and intelligence we have gathered point to an active and systematic effort on the part of the Iraqi regime to keep key materials and people from the inspectors in direct violation of Resolution 1441. The pattern is not just one of reluctant cooperation, nor is it merely a lack of cooperation. What we see is a deliberate campaign to prevent any meaningful inspection work. <a href="#p123">#</a></p>
<a name="p124"></a><p id="mp124">My colleagues, operative paragraph four of U.N. Resolution 1441, which we lingered over so long last fall, clearly states that false statements and omissions in the declaration and a failure by Iraq at any time to comply with and cooperate fully in the implementation of this resolution shall constitute -- the facts speak for themselves --shall constitute a further material breach of its obligation. <a href="#p124">#</a></p>
<a name="p125"></a><p id="mp125">We wrote it this way to give Iraq an early test -- to give Iraq an early test. Would they give an honest declaration and would they early on indicate a willingness to cooperate with the inspectors? It was designed to be an early test. <a href="#p125">#</a></p>
<a name="p126"></a><p id="mp126">They failed that test. By this standard, the standard of this operative paragraph, I believe that Iraq is now in further material breach of its obligations. I believe this conclusion is irrefutable and undeniable. <a href="#p126">#</a></p>
<a name="p127"></a><p id="mp127">Iraq has now placed itself in danger of the serious consequences called for in U.N. Resolution 1441. And this body places itself in danger of irrelevance if it allows Iraq to continue to defy its will without responding effectively and immediately. <a href="#p127">#</a></p>

<a name="p128"></a><p id="mp128">The issue before us is not how much time we are willing to give the inspectors to be frustrated by Iraqi obstruction. But how much longer are we willing to put up with Iraq&#39;s noncompliance before we, as a council, we, as the United Nations, say: &quot;Enough. Enough.&quot; <a href="#p128">#</a></p>
<a name="p129"></a><p id="mp129">The gravity of this moment is matched by the gravity of the threat that Iraq&#39;s weapons of mass destruction pose to the world. Let me now turn to those deadly weapons programs and describe why they are real and present dangers to the region and to the world.  <a href="#p129">#</a></p></div>
<div id="h4"><h2>Part 5: Biological weapons program <a href="#h4" name="h4">#</a></h2>
<a name="p130"></a><p id="mp130">First, biological weapons. We have talked frequently here about biological weapons. By way of introduction and history, I think there are just three quick points I need to make. <a href="#p130">#</a></p>
<a name="p131"></a><p id="mp131">First, you will recall that it took UNSCOM four long and frustrating years to pry -- to pry -- an admission out of Iraq that it had biological weapons. <a href="#p131">#</a></p>
<a name="p132"></a><p id="mp132">Second, when Iraq finally admitted having these weapons in 1995, the quantities were vast. Less than a teaspoon of dry anthrax, a little bit about this amount -- this is just about the amount of a teaspoon -- less than a teaspoon full of dry anthrax in an envelope shutdown the United States Senate in the fall of 2001. This forced several hundred people to undergo emergency medical treatment and killed two postal workers just from an amount just about this quantity that was inside of an envelope. <a href="#p132">#</a></p>

<a name="p133"></a><p id="mp133">Iraq declared 8,500 liters of anthrax, but UNSCOM estimates that Saddam Hussein could have produced 25,000 liters. If concentrated into this dry form, this amount would be enough to fill tens upon tens upon tens of thousands of teaspoons. And Saddam Hussein has not verifiably accounted for even one teaspoon-full of this deadly material. <a href="#p133">#</a></p>
<a name="p134"></a><p id="mp134">And that is my third point. And it is key. The Iraqis have never accounted for all of the biological weapons they admitted they had and we know they had. They have never accounted for all the organic material used to make them. And they have not accounted for many of the weapons filled with these agents such as there are 400 bombs. This is evidence, not conjecture. This is true. This is all well-documented. <a href="#p134">#</a></p>
<a name="p135"></a><p id="mp135">Dr. Blix told this council that Iraq has provided little evidence to verify anthrax production and no convincing evidence of its destruction. It should come as no shock then, that since Saddam Hussein forced out the last inspectors in 1998, we have amassed much intelligence indicating that Iraq is continuing to make these weapons. <a href="#p135">#</a></p>
<a name="p136"></a><p id="mp136">One of the most worrisome things that emerges from the thick intelligence file we have on Iraq&#39;s biological weapons is the existence of mobile production facilities used to make biological agents. <a href="#p136">#</a></p>
<a name="p137"></a><p id="mp137">Let me take you inside that intelligence file and share with you what we know from eye witness accounts. We have firsthand descriptions of biological weapons factories on wheels and on rails. <a href="#p137">#</a></p>
<a name="p138"></a><p id="mp138">The trucks and train cars are easily moved and are designed to evade detection by inspectors. In a matter of months, they can produce a quantity of biological poison equal to the entire amount that Iraq claimed to have produced in the years prior to the Gulf War. <a href="#p138">#</a></p>

<a name="p139"></a><p id="mp139">Although Iraq&#39;s mobile production program began in the mid-1990s, U.N. inspectors at the time only had vague hints of such programs. Confirmation came later, in the year 2000. <a href="#p139">#</a></p>
<a name="p140"></a><p id="mp140">The source was an eye witness, an Iraqi chemical engineer who supervised one of these facilities. He actually was present during biological agent production runs. He was also at the site when an accident occurred in 1998. Twelve technicians died from exposure to biological agents. <a href="#p140">#</a></p>
<a name="p141"></a><p id="mp141">He reported that when UNSCOM was in country and inspecting, the biological weapons agent production always began on Thursdays at midnight because Iraq thought UNSCOM would not inspect on the Muslim Holy Day, Thursday night through Friday. He added that this was important because the units could not be broken down in the middle of a production run, which had to be completed by Friday evening before the inspectors might arrive again. <a href="#p141">#</a></p>
<a name="p142"></a><p id="mp142">This defector is currently hiding in another country with the certain knowledge that Saddam Hussein will kill him if he finds him. His eye-witness account of these mobile production facilities has been corroborated by other sources. <a href="#p142">#</a></p>
<a name="p143"></a><p id="mp143">A second source, an Iraqi civil engineer in a position to know the details of the program, confirmed the existence of transportable facilities moving on trailers. <a href="#p143">#</a></p>
<a name="p144"></a><p id="mp144">A third source, also in a position to know, reported in summer 2002 that Iraq had manufactured mobile production systems mounted on road trailer units and on rail cars. <a href="#p144">#</a></p>

<a name="p145"></a><p id="mp145">Finally, a fourth source, an Iraqi major, who defected, confirmed that Iraq has mobile biological research laboratories, in addition to the production facilities I mentioned earlier. <a href="#p145">#</a></p>
<a name="p146"></a><p id="mp146">We have diagrammed what our sources reported about these mobile facilities. Here you see both truck and rail car-mounted mobile factories. The description our sources gave us of the technical features required by such facilities are highly detailed and extremely accurate. As these drawings based on their description show, we know what the fermenters look like, we know what the tanks, pumps, compressors and other parts look like. We know how they fit together. We know how they work. And we know a great deal about the platforms on which they are mounted. <a href="#p146">#</a></p>
<a name="p147"></a><p id="mp147">As shown in this diagram, these factories can be concealed easily, either by moving ordinary-looking trucks and rail cars along Iraq&#39;s thousands of miles of highway or track, or by parking them in a garage or warehouse or somewhere in Iraq&#39;s extensive system of underground tunnels and bunkers. <a href="#p147">#</a></p>
<a name="p148"></a><p id="mp148">We know that Iraq has at lest seven of these mobile biological agent factories. The truck-mounted ones have at least two or three trucks each. That means that the mobile production facilities are very few, perhaps 18 trucks that we know of -- there may be more -- but perhaps 18 that we know of. Just imagine trying to find 18 trucks among the thousands and thousands of trucks that travel the roads of Iraq every single day. <a href="#p148">#</a></p>
<a name="p149"></a><p id="mp149">It took the inspectors four years to find out that Iraq was making biological agents. How long do you think it will take the inspectors to find even one of these 18 trucks without Iraq coming forward, as they are supposed to, with the information about these kinds of capabilities? <a href="#p149">#</a></p>
<a name="p150"></a><p id="mp150">Ladies and gentlemen, these are sophisticated facilities. For example, they can produce anthrax and botulism toxin. In fact, they can produce enough dry biological agent in a single month to kill thousands upon thousands of people. And dry agent of this type is the most lethal form for human beings. <a href="#p150">#</a></p>

<a name="p151"></a><p id="mp151">By 1998, U.N. experts agreed that the Iraqis had perfected drying techniques for their biological weapons programs. Now, Iraq has incorporated this drying expertise into these mobile production facilities. <a href="#p151">#</a></p>
<a name="p152"></a><p id="mp152">We know from Iraq&#39;s past admissions that it has successfully weaponized not only anthrax, but also other biological agents, including botulism toxin, aflatoxin and ricin. <a href="#p152">#</a></p>
<a name="p153"></a><p id="mp153">But Iraq&#39;s research efforts did not stop there. Saddam Hussein has investigated dozens of biological agents causing diseases such as gas gangrene, plague, typhus, tetanus, cholera, camelpox and hemorrhagic fever, and he also has the wherewithal to develop smallpox. <a href="#p153">#</a></p>
<a name="p154"></a><p id="mp154">The Iraqi regime has also developed ways to disburse lethal biological agents, widely and discriminately into the water supply, into the air. For example, Iraq had a program to modify aerial fuel tanks for Mirage jets. This video of an Iraqi test flight obtained by UNSCOM some years ago shows an Iraqi F-1 Mirage jet aircraft. Note the spray coming from beneath the Mirage; that is 2,000 liters of simulated anthrax that a jet is spraying. <a href="#p154">#</a></p>
<a name="p155"></a><p id="mp155">In 1995, an Iraqi military officer, Mujahid Sali Abdul Latif (ph), told inspectors that Iraq intended the spray tanks to be mounted onto a MiG-21 that had been converted into an unmanned aerial vehicle, or a UAV. UAVs outfitted with spray tanks constitute an ideal method for launching a terrorist attack using biological weapons. <a href="#p155">#</a></p>
<a name="p156"></a><p id="mp156">Iraq admitted to producing four spray tanks. But to this day, it has provided no credible evidence that they were destroyed, evidence that was required by the international community. <a href="#p156">#</a></p>

<a name="p157"></a><p id="mp157">There can be no doubt that Saddam Hussein has biological weapons and the capability to rapidly produce more, many more. And he has the ability to dispense these lethal poisons and diseases in ways that can cause massive death and destruction. If biological weapons seem too terrible to contemplate, chemical weapons are equally chilling. <a href="#p157">#</a></p>
<a name="p158"></a><p id="mp158">UNMOVIC already laid out much of this, and it is documented for all of us to read in UNSCOM&#39;s 1999 report on the subject. <a href="#p158">#</a></p>
<a name="p159"></a><p id="mp159">Let me set the stage with three key points that all of us need to keep in mind: First, Saddam Hussein has used these horrific weapons on another country and on his own people. In fact, in the history of chemical warfare, no country has had more battlefield experience with chemical weapons since World War I than Saddam Hussein&#39;s Iraq.  <a href="#p159">#</a></p></div>
<div id="h5"><h2>Part 6: Chemical weapons <a href="#h5" name="h5">#</a></h2>
<a name="p160"></a><p id="mp160">Second, as with biological weapons, Saddam Hussein has never accounted for vast amounts of chemical weaponry: 550 artillery shells with mustard, 30,000 empty munitions and enough precursors to increase his stockpile to as much as 500 tons of chemical agents. If we consider just one category of missing weaponry -- 6,500 bombs from the Iran-Iraq war -- UNMOVIC says the amount of chemical agent in them would be in the order of 1,000 tons. These quantities of chemical weapons are now unaccounted for. <a href="#p160">#</a></p>
<a name="p161"></a><p id="mp161">Dr. Blix has quipped that, quote, &quot;Mustard gas is not (inaudible) You are supposed to know what you did with it.&quot; <a href="#p161">#</a></p>

<a name="p162"></a><p id="mp162">We believe Saddam Hussein knows what he did with it, and he has not come clean with the international community. We have evidence these weapons existed. What we don&#39;t have is evidence from Iraq that they have been destroyed or where they are. That is what we are still waiting for. <a href="#p162">#</a></p>
<a name="p163"></a><p id="mp163">Third point, Iraq&#39;s record on chemical weapons is replete with lies. It took years for Iraq to finally admit that it had produced four tons of the deadly nerve agent, VX. A single drop of VX on the skin will kill in minutes. Four tons. <a href="#p163">#</a></p>
<a name="p164"></a><p id="mp164">The admission only came out after inspectors collected documentation as a result of the defection of Hussein Kamal, Saddam Hussein&#39;s late son-in-law. UNSCOM also gained forensic evidence that Iraq had produced VX and put it into weapons for delivery. Yet, to this day, Iraq denies it had ever weaponized VX. <a href="#p164">#</a></p>
<a name="p165"></a><p id="mp165">And on January 27, UNMOVIC told this council that it has information that conflicts with the Iraqi account of its VX program. <a href="#p165">#</a></p>
<a name="p166"></a><p id="mp166">We know that Iraq has embedded key portions of its illicit chemical weapons infrastructure within its legitimate civilian industry. To all outward appearances, even to experts, the infrastructure looks like an ordinary civilian operation. Illicit and legitimate production can go on simultaneously; or, on a dime, this dual-use infrastructure can turn from clandestine to commercial and then back again. <a href="#p166">#</a></p>
<a name="p167"></a><p id="mp167">These inspections would be unlikely, any inspections of such facilities would be unlikely to turn up anything prohibited, especially if there is any warning that the inspections are coming. Call it ingenuous or evil genius, but the Iraqis deliberately designed their chemical weapons programs to be inspected. It is infrastructure with a built-in ally. <a href="#p167">#</a></p>

<a name="p168"></a><p id="mp168">Under the guise of dual-use infrastructure, Iraq has undertaken an effort to reconstitute facilities that were closely associated with its past program to develop and produce chemical weapons. <a href="#p168">#</a></p>
<a name="p169"></a><p id="mp169">For example, Iraq has rebuilt key portions of the Tariq state establishment. Tariq includes facilities designed specifically for Iraq&#39;s chemical weapons program and employs key figures from past programs. <a href="#p169">#</a></p>
<a name="p170"></a><p id="mp170">That&#39;s the production end of Saddam&#39;s chemical weapons business. <a href="#p170">#</a></p>
<a name="p171"></a><p id="mp171">What about the delivery end? <a href="#p171">#</a></p>
<a name="p172"></a><p id="mp172">I&#39;m going to show you a small part of a chemical complex called al-Moussaid (ph), a site that Iraq has used for at least three years to transship chemical weapons from production facilities out to the field. <a href="#p172">#</a></p>
<a name="p173"></a><p id="mp173">In May 2002, our satellites photographed the unusual activity in this picture. Here we see cargo vehicles are again at this transshipment point, and we can see that they are accompanied by a decontamination vehicle associated with biological or chemical weapons activity. <a href="#p173">#</a></p>

<a name="p174"></a><p id="mp174">What makes this picture significant is that we have a human source who has corroborated that movement of chemical weapons occurred at this site at that time. So it&#39;s not just the photo, and it&#39;s not an individual seeing the photo. It&#39;s the photo and then the knowledge of an individual being brought together to make the case. <a href="#p174">#</a></p>
<a name="p175"></a><p id="mp175">This photograph of the site taken two months later in July shows not only the previous site, which is the figure in the middle at the top with the bulldozer sign near it, it shows that this previous site, as well as all of the other sites around the site, have been fully bulldozed and graded. The topsoil has been removed. The Iraqis literally removed the crust of the earth from large portions of this site in order to conceal chemical weapons evidence that would be there from years of chemical weapons activity. <a href="#p175">#</a></p>
<a name="p176"></a><p id="mp176">To support its deadly biological and chemical weapons programs, Iraq procures needed items from around the world using an extensive clandestine network. What we know comes largely from intercepted communications and human sources who are in a position to know the facts. <a href="#p176">#</a></p>
<a name="p177"></a><p id="mp177">Iraq&#39;s procurement efforts include equipment that can filter and separate micro-organisms and toxins involved in biological weapons, equipment that can be used to concentrate the agent, growth media that can be used to continue producing anthrax and botulism toxin, sterilization equipment for laboratories, glass-lined reactors and specialty pumps that can handle corrosive chemical weapons agents and recursors, large amounts of vinyl chloride, a precursor for nerve and blister agents, and other chemicals such as sodium sulfide, an important mustard agent precursor. <a href="#p177">#</a></p>
<a name="p178"></a><p id="mp178">Now, of course, Iraq will argue that these items can also be used for legitimate purposes. But if that is true, why do we have to learn about them by intercepting communications and risking the lives of human agents? With Iraq&#39;s well documented history on biological and chemical weapons, why should any of us give Iraq the benefit of the doubt? I don&#39;t, and I don&#39;t think you will either after you hear this next intercept. <a href="#p178">#</a></p>
<a name="p179"></a><p id="mp179">Just a few weeks ago, we intercepted communications between two commanders in Iraq&#39;s Second Republican Guard Corps. One commander is going to be giving an instruction to the other. You will hear as this unfolds that what he wants to communicate to the other guy, he wants to make sure the other guy hears clearly, to the point of repeating it so that it gets written down and completely understood. Listen. <a href="#p179">#</a></p>

<a name="p180"></a><p id="mp180">(BEGIN AUDIO TAPE) <a href="#p180">#</a></p>
<a name="p181"></a><p id="mp181">(Speaking in Foreign Language.) <a href="#p181">#</a></p>
<a name="p182"></a><p id="mp182">(END AUDIO TAPE) <a href="#p182">#</a></p>
<a name="p183"></a><p id="mp183">Let&#39;s review a few selected items of this conversation. <a href="#p183">#</a></p>
<a name="p184"></a><p id="mp184">Two officers talking to each other on the radio want to make sure that nothing is misunderstood: <a href="#p184">#</a></p>
<a name="p185"></a><p id="mp185">&quot;Remove. Remove.&quot; <a href="#p185">#</a></p>

<a name="p186"></a><p id="mp186">The expression, the expression, &quot;I got it.&quot; <a href="#p186">#</a></p>
<a name="p187"></a><p id="mp187">&quot;Nerve agents. Nerve agents. Wherever it comes up.&quot; <a href="#p187">#</a></p>
<a name="p188"></a><p id="mp188">&quot;Got it.&quot; <a href="#p188">#</a></p>
<a name="p189"></a><p id="mp189">&quot;Wherever it comes up.&quot; <a href="#p189">#</a></p>
<a name="p190"></a><p id="mp190">&quot;In the wireless instructions, in the instructions.&quot; <a href="#p190">#</a></p>
<a name="p191"></a><p id="mp191">&quot;Correction. No. In the wireless instructions.&quot; <a href="#p191">#</a></p>

<a name="p192"></a><p id="mp192">&quot;Wireless. I got it.&quot; <a href="#p192">#</a></p>
<a name="p193"></a><p id="mp193">Why does he repeat it that way? Why is he so forceful in making sure this is understood? And why did he focus on wireless instructions? Because the senior officer is concerned that somebody might be listening. <a href="#p193">#</a></p>
<a name="p194"></a><p id="mp194">Well, somebody was. <a href="#p194">#</a></p>
<a name="p195"></a><p id="mp195">&quot;Nerve agents. Stop talking about it. They are listening to us. Don&#39;t give any evidence that we have these horrible agents.&quot; <a href="#p195">#</a></p>
<a name="p196"></a><p id="mp196">Well, we know that they do. And this kind of conversation confirms it. <a href="#p196">#</a></p>
<a name="p197"></a><p id="mp197">Our conservative estimate is that Iraq today has a stockpile of between 100 and 500 tons of chemical weapons agent. That is enough agent to fill 16,000 battlefield rockets. <a href="#p197">#</a></p>

<a name="p198"></a><p id="mp198">Even the low end of 100 tons of agent would enable Saddam Hussein to cause mass casualties across more than 100 square miles of territory, an area nearly five times the size of Manhattan. <a href="#p198">#</a></p>
<a name="p199"></a><p id="mp199">Let me remind you that, of the 122 millimeter chemical warheads, that the U.N. inspectors found recently, this discovery could very well be, as has been noted, the tip of the submerged iceberg. The question before us, all my friends, is when will we see the rest of the submerged iceberg? <a href="#p199">#</a></p>
<a name="p200"></a><p id="mp200">Saddam Hussein has chemical weapons. Saddam Hussein has used such weapons. And Saddam Hussein has no compunction about using them again, against his neighbors and against his own people. <a href="#p200">#</a></p>
<a name="p201"></a><p id="mp201">And we have sources who tell us that he recently has authorized his field commanders to use them. He wouldn&#39;t be passing out the orders if he didn&#39;t have the weapons or the intent to use them. <a href="#p201">#</a></p>
<a name="p202"></a><p id="mp202">We also have sources who tell us that, since the 1980s, Saddam&#39;s regime has been experimenting on human beings to perfect its biological or chemical weapons. <a href="#p202">#</a></p>
<a name="p203"></a><p id="mp203">A source said that 1,600 death row prisoners were transferred in 1995 to a special unit for such experiments. An eye witness saw prisoners tied down to beds, experiments conducted on them, blood oozing around the victim&#39;s mouths and autopsies performed to confirm the effects on the prisoners. Saddam Hussein&#39;s humanity -- inhumanity has no limits.  <a href="#p203">#</a></p></div>

<div id="h6"><h2>Part 7: Nuclear weapons <a href="#h6" name="h6">#</a></h2>
<a name="p204"></a><p id="mp204">Let me turn now to nuclear weapons. We have no indication that Saddam Hussein has ever abandoned his nuclear weapons program. <a href="#p204">#</a></p>
<a name="p205"></a><p id="mp205">On the contrary, we have more than a decade of proof that he remains determined to acquire nuclear weapons. <a href="#p205">#</a></p>
<a name="p206"></a><p id="mp206">To fully appreciate the challenge that we face today, remember that, in 1991, the inspectors searched Iraq&#39;s primary nuclear weapons facilities for the first time. And they found nothing to conclude that Iraq had a nuclear weapons program. <a href="#p206">#</a></p>
<a name="p207"></a><p id="mp207">But based on defector information in May of 1991, Saddam Hussein&#39;s lie was exposed. In truth, Saddam Hussein had a massive clandestine nuclear weapons program that covered several different techniques to enrich uranium, including electromagnetic isotope separation, gas centrifuge, and gas diffusion. We estimate that this illicit program cost the Iraqis several billion dollars. <a href="#p207">#</a></p>
<a name="p208"></a><p id="mp208">Nonetheless, Iraq continued to tell the IAEA that it had no nuclear weapons program. If Saddam had not been stopped, Iraq could have produced a nuclear bomb by 1993, years earlier than most worse-case assessments that had been made before the war. <a href="#p208">#</a></p>

<a name="p209"></a><p id="mp209">In 1995, as a result of another defector, we find out that, after his invasion of Kuwait, Saddam Hussein had initiated a crash program to build a crude nuclear weapon in violation of Iraq&#39;s U.N. obligations. <a href="#p209">#</a></p>
<a name="p210"></a><p id="mp210">Saddam Hussein already possesses two out of the three key components needed to build a nuclear bomb. He has a cadre of nuclear scientists with the expertise, and he has a bomb design. <a href="#p210">#</a></p>
<a name="p211"></a><p id="mp211">Since 1998, his efforts to reconstitute his nuclear program have been focused on acquiring the third and last component, sufficient fissile material to produce a nuclear explosion. To make the fissile material, he needs to develop an ability to enrich uranium. <a href="#p211">#</a></p>
<a name="p212"></a><p id="mp212">Saddam Hussein is determined to get his hands on a nuclear bomb. <a href="#p212">#</a></p>
<a name="p213"></a><p id="mp213">He is so determined that he has made repeated covert attempts to acquire high-specification aluminum tubes from 11 different countries, even after inspections resumed. <a href="#p213">#</a></p>
<a name="p214"></a><p id="mp214">These tubes are controlled by the Nuclear Suppliers Group precisely because they can be used as centrifuges for enriching uranium. By now, just about everyone has heard of these tubes, and we all know that there are differences of opinion. There is controversy about what these tubes are for. <a href="#p214">#</a></p>

<a name="p215"></a><p id="mp215">Most U.S. experts think they are intended to serve as rotors in centrifuges used to enrich uranium. Other experts, and the Iraqis themselves, argue that they are really to produce the rocket bodies for a conventional weapon, a multiple rocket launcher. <a href="#p215">#</a></p>
<a name="p216"></a><p id="mp216">Let me tell you what is not controversial about these tubes. <a href="#p216">#</a></p>
<a name="p217"></a><p id="mp217">First, all the experts who have analyzed the tubes in our possession agree that they can be adapted for centrifuge use. Second, Iraq had no business buying them for any purpose. They are banned for Iraq. <a href="#p217">#</a></p>
<a name="p218"></a><p id="mp218">I am no expert on centrifuge tubes, but just as an old Army trooper, I can tell you a couple of things: First, it strikes me as quite odd that these tubes are manufactured to a tolerance that far exceeds U.S. requirements for comparable rockets. <a href="#p218">#</a></p>
<a name="p219"></a><p id="mp219">Maybe Iraqis just manufacture their conventional weapons to a higher standard than we do, but I don&#39;t think so. <a href="#p219">#</a></p>
<a name="p220"></a><p id="mp220">Second, we actually have examined tubes from several different batches that were seized clandestinely before they reached Baghdad. What we notice in these different batches is a progression to higher and higher levels of specification, including, in the latest batch, an anodized coating on extremely smooth inner and outer surfaces. Why would they continue refining the specifications, go to all that trouble for something that, if it was a rocket, would soon be blown into shrapnel when it went off? <a href="#p220">#</a></p>

<a name="p221"></a><p id="mp221">The high tolerance aluminum tubes are only part of the story. We also have intelligence from multiple sources that Iraq is attempting to acquire magnets and high-speed balancing machines; both items can be used in a gas centrifuge program to enrich uranium. <a href="#p221">#</a></p>
<a name="p222"></a><p id="mp222">In 1999 and 2000, Iraqi officials negotiated with firms in Romania, India, Russia and Slovenia for the purchase of a magnet production plant. Iraq wanted the plant to produce magnets weighing 20 to 30 grams. That&#39;s the same weight as the magnets used in Iraq&#39;s gas centrifuge program before the Gulf War. This incident linked with the tubes is another indicator of Iraq&#39;s attempt to reconstitute its nuclear weapons program. <a href="#p222">#</a></p>
<a name="p223"></a><p id="mp223">Intercepted communications from mid-2000 through last summer show that Iraq front companies sought to buy machines that can be used to balance gas centrifuge rotors. One of these companies also had been involved in a failed effort in 2001 to smuggle aluminum tubes into Iraq. <a href="#p223">#</a></p>
<a name="p224"></a><p id="mp224">People will continue to debate this issue, but there is no doubt in my mind, these illicit procurement efforts show that Saddam Hussein is very much focused on putting in place the key missing piece from his nuclear weapons program, the ability to produce fissile material. <a href="#p224">#</a></p>
<a name="p225"></a><p id="mp225">He also has been busy trying to maintain the other key parts of his nuclear program, particularly his cadre of key nuclear scientists. <a href="#p225">#</a></p>
<a name="p226"></a><p id="mp226">It is noteworthy that, over the last 18 months, Saddam Hussein has paid increasing personal attention to Iraqi&#39;s top nuclear scientists, a group that the governmental-controlled press calls openly, his nuclear mujahedeen. He regularly exhorts them and praises their progress. Progress toward what end? <a href="#p226">#</a></p>

<a name="p227"></a><p id="mp227">Long ago, the Security Council, this council, required Iraq to halt all nuclear activities of any kind.  <a href="#p227">#</a></p></div>
<div id="h7"><h2>Part 8: Prohibited arms systems <a href="#h7" name="h7">#</a></h2>
<a name="p228"></a><p id="mp228">Let me talk now about the systems Iraq is developing to deliver weapons of mass destruction, in particular Iraq&#39;s ballistic missiles and unmanned aerial vehicles, UAVs. <a href="#p228">#</a></p>
<a name="p229"></a><p id="mp229">First, missiles. We all remember that before the Gulf War Saddam Hussein&#39;s goal was missiles that flew not just hundreds, but thousands of kilometers. He wanted to strike not only his neighbors, but also nations far beyond his borders. <a href="#p229">#</a></p>
<a name="p230"></a><p id="mp230">While inspectors destroyed most of the prohibited ballistic missiles, numerous intelligence reports over the past decade, from sources inside Iraq, indicate that Saddam Hussein retains a covert force of up to a few dozen Scud variant ballistic missiles. These are missiles with a range of 650 to 900 kilometers. <a href="#p230">#</a></p>
<a name="p231"></a><p id="mp231">We know from intelligence and Iraq&#39;s own admissions that Iraq&#39;s alleged permitted ballistic missiles, the al-Samud II and the al-Fatah , violate the 150-kilometer limit established by this council in Resolution 687. These are prohibited systems. <a href="#p231">#</a></p>

<a name="p232"></a><p id="mp232">UNMOVIC has also reported that Iraq has illegally important 380 SA-2 rocket engines. These are likely for use in the al-Samud II. Their import was illegal on three counts. Resolution 687 prohibited all military shipments into Iraq. UNSCOM specifically prohibited use of these engines in surface-to-surface missiles. And finally, as we have just noted, they are for a system that exceeds the150-kilometer range limit. <a href="#p232">#</a></p>
<a name="p233"></a><p id="mp233">Worst of all, some of these engines were acquired as late as December -- after this council passed Resolution 1441. <a href="#p233">#</a></p>
<a name="p234"></a><p id="mp234">What I want you to know today is that Iraq has programs that are intended to produce ballistic missiles that fly over 1,000 kilometers. <a href="#p234">#</a></p>
<a name="p235"></a><p id="mp235">One program is pursuing a liquid fuel missile that would be able to fly more than 1,200 kilometers. And you can see from this map, as well as I can, who will be in danger of these missiles. <a href="#p235">#</a></p>
<a name="p236"></a><p id="mp236">As part of this effort, another little piece of evidence, Iraq has built an engine test stand that is larger than anything it has ever had. Notice the dramatic difference in size between the test stand on the left, the old one, and the new one on the right. Note the large exhaust vent. This is where the flame from the engine comes out. The exhaust on the right test stand is five times longer than the one on the left. The one on the left was used for short-range missile. The one on the right is clearly intended for long-range missiles that can fly 1,200 kilometers. <a href="#p236">#</a></p>
<a name="p237"></a><p id="mp237">This photograph was taken in April of 2002. Since then, the test stand has been finished and a roof has been put over it so it will be harder for satellites to see what&#39;s going on underneath the test stand. <a href="#p237">#</a></p>

<a name="p238"></a><p id="mp238">Saddam Hussein&#39;s intentions have never changed. He is not developing the missiles for self-defense. These are missiles that Iraq wants in order to project power, to threaten, and to deliver chemical, biological and, if we let him, nuclear warheads. <a href="#p238">#</a></p>
<a name="p239"></a><p id="mp239">Now, unmanned aerial vehicles, UAVs. <a href="#p239">#</a></p>
<a name="p240"></a><p id="mp240">Iraq has been working on a variety of UAVs for more than a decade. This is just illustrative of what a UAV would look like. <a href="#p240">#</a></p>
<a name="p241"></a><p id="mp241">This effort has included attempts to modify for unmanned flight the MiG-21 and with greater success an aircraft called the L-29. <a href="#p241">#</a></p>
<a name="p242"></a><p id="mp242">However, Iraq is now concentrating not on these airplanes, but on developing and testing smaller UAVs, such as this. <a href="#p242">#</a></p>
<a name="p243"></a><p id="mp243">UAVs are well suited for dispensing chemical and biological weapons. <a href="#p243">#</a></p>

<a name="p244"></a><p id="mp244">There is ample evidence that Iraq has dedicated much effort to developing and testing spray devices that could be adapted for UAVs. And of the little that Saddam Hussein told us about UAVs, he has not told the truth. One of these lies is graphically and indisputably demonstrated by intelligence we collected on June 27, last year. <a href="#p244">#</a></p>
<a name="p245"></a><p id="mp245">According to Iraq&#39;s December 7 declaration, its UAVs have a range of only 80 kilometers. But we detected one of Iraq&#39;s newest UAVs in a test flight that went 500 kilometers nonstop on autopilot in the race track pattern depicted here. <a href="#p245">#</a></p>
<a name="p246"></a><p id="mp246">Not only is this test well in excess of the 150 kilometers that the United Nations permits, the test was left out of Iraq&#39;s December 7th declaration. The UAV was flown around and around and around in a circle. And so, that its 80 kilometer limit really was 500 kilometers unrefueled and on autopilot, violative of all of its obligations under 1441. <a href="#p246">#</a></p>
<a name="p247"></a><p id="mp247">The linkages over the past 10 years between Iraq&#39;s UAV program and biological and chemical warfare agents are of deep concern to us. <a href="#p247">#</a></p>
<a name="p248"></a><p id="mp248">Iraq could use these small UAVs which have a wingspan of only a few meters to deliver biological agents to its neighbors or if transported, to other countries, including the United States. <a href="#p248">#</a></p>
<a name="p249"></a><p id="mp249">My friends, the information I have presented to you about these terrible weapons and about Iraq&#39;s continued flaunting of its obligations under Security Council Resolution 1441 links to a subject I now want to spend a little bit of time on. And that has to do with terrorism.  <a href="#p249">#</a></p></div>

<div id="h8"><h2>Part 9: Ties to al Qaeda <a href="#h8" name="h8">#</a></h2>
<a name="p250"></a><p id="mp250">Our concern is not just about these illicit weapons. It&#39;s the way that these illicit weapons can be connected to terrorists and terrorist organizations that have no compunction about using such devices against innocent people around the world. <a href="#p250">#</a></p>
<a name="p251"></a><p id="mp251">Iraq and terrorism go back decades. Baghdad trains Palestine Liberation Front members in small arms and explosives. Saddam uses the Arab Liberation Front to funnel money to the families of Palestinian suicide bombers in order to prolong the intifada. And it&#39;s no secret that Saddam&#39;s own intelligence service was involved in dozens of attacks or attempted assassinations in the 1990s. <a href="#p251">#</a></p>
<a name="p252"></a><p id="mp252">But what I want to bring to your attention today is the potentially much more sinister nexus between Iraq and the al Qaeda terrorist network, a nexus that combines classic terrorist organizations and modern methods of murder. Iraq today harbors a deadly terrorist network headed by Abu Musab Zarqawi, an associate and collaborator of Osama bin Laden and his al Qaeda lieutenants. <a href="#p252">#</a></p>
<a name="p253"></a><p id="mp253">Zarqawi, a Palestinian born in Jordan, fought in the Afghan war more than a decade ago. Returning to Afghanistan in 2000, he oversaw a terrorist training camp. One of his specialities and one of the specialties of this camp is poisons. When our coalition ousted the Taliban, the Zarqawi network helped establish another poison and explosive training center camp. And this camp is located in northeastern Iraq. <a href="#p253">#</a></p>
<a name="p254"></a><p id="mp254">You see a picture of this camp. <a href="#p254">#</a></p>

<a name="p255"></a><p id="mp255">The network is teaching its operatives how to produce ricin and other poisons. Let me remind you how ricin works. Less than a pinch -- image a pinch of salt -- less than a pinch of ricin, eating just this amount in your food, would cause shock followed by circulatory failure. Death comes within 72 hours and there is no antidote, there is no cure. It is fatal. <a href="#p255">#</a></p>
<a name="p256"></a><p id="mp256">Those helping to run this camp are Zarqawi lieutenants operating in northern Kurdish areas outside Saddam Hussein&#39;s controlled Iraq. <a href="#p256">#</a></p>
<a name="p257"></a><p id="mp257">But Baghdad has an agent in the most senior levels of the radical organization, Ansar al-Islam, that controls this corner of Iraq. In 2000 this agent offered al Qaeda safe haven in the region. After we swept al Qaeda from Afghanistan, some of its members accepted this safe haven. They remain their today. <a href="#p257">#</a></p>
<a name="p258"></a><p id="mp258">Zarqawi&#39;s activities are not confined to this small corner of northeast Iraq. He traveled to Baghdad in May 2002 for medical treatment, staying in the capital of Iraq for two months while he recuperated to fight another day. <a href="#p258">#</a></p>
<a name="p259"></a><p id="mp259">During this stay, nearly two dozen extremists converged on Baghdad and established a base of operations there. These al Qaeda affiliates, based in Baghdad, now coordinate the movement of people, money and supplies into and throughout Iraq for his network, and they&#39;ve now been operating freely in the capital for more than eight months. <a href="#p259">#</a></p>
<a name="p260"></a><p id="mp260">Iraqi officials deny accusations of ties with al Qaeda. These denials are simply not credible. Last year an al Qaeda associate bragged that the situation in Iraq was, quote, &quot;good,&quot; that Baghdad could be transited quickly. <a href="#p260">#</a></p>

<a name="p261"></a><p id="mp261">We know these affiliates are connected to Zarqawi because they remain even today in regular contact with his direct subordinates, including the poison cell plotters, and they are involved in moving more than money and materiel. <a href="#p261">#</a></p>
<a name="p262"></a><p id="mp262">Last year, two suspected al Qaeda operatives were arrested crossing from Iraq into Saudi Arabia. They were linked to associates of the Baghdad cell, and one of them received training in Afghanistan on how to use cyanide. From his terrorist network in Iraq, Zarqawi can direct his network in the Middle East and beyond. <a href="#p262">#</a></p>
<a name="p263"></a><p id="mp263">We, in the United States, all of us at the State Department, and the Agency for International Development -- we all lost a dear friend with the cold-blooded murder of Mr. Lawrence Foley in Amman, Jordan, last October -- a despicable act was committed that day. The assassination of an individual whose sole mission was to assist the people of Jordan. The captured assassin says his cell received money and weapons from Zarqawi for that murder. <a href="#p263">#</a></p>
<a name="p264"></a><p id="mp264">After the attack, an associate of the assassin left Jordan to go to Iraq to obtain weapons and explosives for further operations. Iraqi officials protest that they are not aware of the whereabouts of Zarqawi or of any of his associates. Again, these protests are not credible. We know of Zarqawi&#39;s activities in Baghdad. I described them earlier. <a href="#p264">#</a></p>
<a name="p265"></a><p id="mp265">And now let me add one other fact. We asked a friendly security service to approach Baghdad about extraditing Zarqawi and providing information about him and his close associates. This service contacted Iraqi officials twice, and we passed details that should have made it easy to find Zarqawi. The network remains in Baghdad. Zarqawi still remains at large to come and go. <a href="#p265">#</a></p>
<a name="p266"></a><p id="mp266">As my colleagues around this table and as the citizens they represent in Europe know, Zarqawi&#39;s terrorism is not confined to the Middle East. Zarqawi and his network have plotted terrorist actions against countries, including France, Britain, Spain, Italy, Germany and Russia. <a href="#p266">#</a></p>

<a name="p267"></a><p id="mp267">According to detainees, Abu Atia, who graduated from Zakawi&#39;s terrorist camp in Afghanistan, tasked at least nine North African extremists in 2001 to travel to Europe to conduct poison and explosive attacks. <a href="#p267">#</a></p>
<a name="p268"></a><p id="mp268">Since last year, members of this network have been apprehended in France, Britain, Spain and Italy. By our last count, 116 operatives connected to this global web have been arrested. <a href="#p268">#</a></p>
<a name="p269"></a><p id="mp269">The chart you are seeing shows the network in Europe. We know about this European network, and we know about its links to Zarqawi, because the detainee who provided the information about the targets also provided the names of members of the network. <a href="#p269">#</a></p>
<a name="p270"></a><p id="mp270">Three of those he identified by name were arrested in France last December. In the apartments of the terrorists, authorities found circuits for explosive devices and a list of ingredients to make toxins. <a href="#p270">#</a></p>
<a name="p271"></a><p id="mp271">The detainee who helped piece this together says the plot also targeted Britain. Later evidence, again, proved him right. When the British unearthed a cell there just last month, one British police officer was murdered during the disruption of the cell. <a href="#p271">#</a></p>
<a name="p272"></a><p id="mp272">We also know that Zarqawi&#39;s colleagues have been active in the Pankisi Gorge, Georgia and in Chechnya, Russia. The plotting to which they are linked is not mere chatter. Members of Zarqawi&#39;s network say their goal was to kill Russians with toxins. <a href="#p272">#</a></p>

<a name="p273"></a><p id="mp273">We are not surprised that Iraq is harboring Zarqawi and his subordinates. This understanding builds on decades long experience with respect to ties between Iraq and al Qaeda. <a href="#p273">#</a></p>
<a name="p274"></a><p id="mp274">Going back to the early and mid-1990s, when bin Laden was based in Sudan, an al Qaeda source tells us that Saddam and bin Laden reached an understanding that al Qaeda would no longer support activities against Baghdad. Early al Qaeda ties were forged by secret, high-level intelligence service contacts with al Qaeda, secret Iraqi intelligence high-level contacts with al Qaeda. <a href="#p274">#</a></p>
<a name="p275"></a><p id="mp275">We know members of both organizations met repeatedly and have met at least eight times at very senior levels since the early 1990s. In1996, a foreign security service tells us, that bin Laden met with a senior Iraqi intelligence official in Khartoum, and later met the director of the Iraqi intelligence service. <a href="#p275">#</a></p>
<a name="p276"></a><p id="mp276">Saddam became more interested as he saw al Qaeda&#39;s appalling attacks. A detained al Qaeda member tells us that Saddam was more willing to assist al Qaeda after the 1998 bombings of our embassies in Kenya and Tanzania. Saddam was also impressed by al Qaeda&#39;s attacks on the USS Cole in Yemen in October 2000. <a href="#p276">#</a></p>
<a name="p277"></a><p id="mp277">Iraqis continued to visit bin Laden in his new home in Afghanistan. A senior defector, one of Saddam&#39;s former intelligence chiefs in Europe, says Saddam sent his agents to Afghanistan sometime in the mid-1990s to provide training to al Qaeda members on document forgery. <a href="#p277">#</a></p>
<a name="p278"></a><p id="mp278">From the late 1990s until 2001, the Iraqi embassy in Pakistan played the role of liaison to the al Qaeda organization. <a href="#p278">#</a></p>

<a name="p279"></a><p id="mp279">Some believe, some claim these contacts do not amount to much. <a href="#p279">#</a></p>
<a name="p280"></a><p id="mp280">They say Saddam Hussein&#39;s secular tyranny and al Qaeda&#39;s religious tyranny do not mix. I am not comforted by this thought. Ambition and hatred are enough to bring Iraq and al Qaeda together, enough so al Qaeda could learn how to build more sophisticated bombs and learn how to forge documents, and enough so that al Qaeda could turn to Iraq for help in acquiring expertise on weapons of mass destruction. <a href="#p280">#</a></p>
<a name="p281"></a><p id="mp281">And the record of Saddam Hussein&#39;s cooperation with other Islamist terrorist organizations is clear. Hamas, for example, opened an office in Baghdad in 1999, and Iraq has hosted conferences attended by Palestine Islamic Jihad. These groups are at the forefront of sponsoring suicide attacks against Israel. <a href="#p281">#</a></p>
<a name="p282"></a><p id="mp282">Al Qaeda continues to have a deep interest in acquiring weapons of mass destruction. As with the story of Zarqawi and his network, I can trace the story of a senior terrorist operative telling how Iraq provided training in these weapons to al Qaeda. <a href="#p282">#</a></p>
<a name="p283"></a><p id="mp283">Fortunately, this operative is now detained, and he has told his story. I will relate it to you now as he, himself, described it. <a href="#p283">#</a></p>
<a name="p284"></a><p id="mp284">This senior al Qaeda terrorist was responsible for one of al Qaeda&#39;s training camps in Afghanistan. <a href="#p284">#</a></p>

<a name="p285"></a><p id="mp285">His information comes firsthand from his personal involvement at senior levels of al Qaeda. He says bin Laden and his top deputy in Afghanistan, deceased al Qaeda leader Mohammed Atef, did not believe that al Qaeda labs in Afghanistan were capable enough to manufacture these chemical or biological agents. They needed to go somewhere else. They had to look outside of Afghanistan for help. Where did they go? Where did they look? They went to Iraq. <a href="#p285">#</a></p>
<a name="p286"></a><p id="mp286">The support that (inaudible) describes included Iraq offering chemical or biological weapons training for two al Qaeda associates beginning in December 2000. He says that a militant known as Abu Abdula Al-Iraqi (ph) had been sent to Iraq several times between 1997and 2000 for help in acquiring poisons and gases. Abdula Al-Iraqi (ph) characterized the relationship he forged with Iraqi officials as successful.  <a href="#p286">#</a></p></div>
<div id="h9"><h2>Part 10: Conclusion <a href="#h9" name="h9">#</a></h2>
<a name="p287"></a><p id="mp287">As I said at the outset, none of this should come as a surprise to any of us. Terrorism has been a tool used by Saddam for decades. Saddam was a supporter of terrorism long before these terrorist networks had a name. And this support continues. The nexus of poisons and terror is new. The nexus of Iraq and terror is old. The combination is lethal. <a href="#p287">#</a></p>
<a name="p288"></a><p id="mp288">With this track record, Iraqi denials of supporting terrorism take the place alongside the other Iraqi denials of weapons of mass destruction. It is all a web of lies. <a href="#p288">#</a></p>
<a name="p289"></a><p id="mp289">When we confront a regime that harbors ambitions for regional domination, hides weapons of mass destruction and provides haven and active support for terrorists, we are not confronting the past, we are confronting the present. And unless we act, we are confronting an even more frightening future. <a href="#p289">#</a></p>

<a name="p290"></a><p id="mp290">My friends, this has been a long and a detailed presentation. <a href="#p290">#</a></p>
<a name="p291"></a><p id="mp291">And I thank you for your patience. But there is one more subject that I would like to touch on briefly. And it should be a subject of deep and continuing concern to this council, Saddam Hussein&#39;s violations of human rights. <a href="#p291">#</a></p>
<a name="p292"></a><p id="mp292">Underlying all that I have said, underlying all the facts and the patterns of behavior that I have identified as Saddam Hussein&#39;s contempt for the will of this council, his contempt for the truth and most damning of all, his utter contempt for human life. Saddam Hussein&#39;s use of mustard and nerve gas against the Kurds in 1988 was one of the 20th century&#39;s most horrible atrocities; 5,000 men, women and children died. <a href="#p292">#</a></p>
<a name="p293"></a><p id="mp293">His campaign against the Kurds from 1987 to &#39;89 included mass summary executions, disappearances, arbitrary jailing, ethnic cleansing and the destruction of some 2,000 villages. He has also conducted ethnic cleansing against the Shiite Iraqis and the Marsh Arabs whose culture has flourished for more than a millennium. Saddam Hussein&#39;s police state ruthlessly eliminates anyone who dares to dissent. Iraq has more forced disappearance cases than any other country, tens of thousands of people reported missing in the past decade. <a href="#p293">#</a></p>
<a name="p294"></a><p id="mp294">Nothing points more clearly to Saddam Hussein&#39;s dangerous intentions and the threat he poses to all of us than his calculated cruelty to his own citizens and to his neighbors. Clearly, Saddam Hussein and his regime will stop at nothing until something stops him. <a href="#p294">#</a></p>
<a name="p295"></a><p id="mp295">For more than 20 years, by word and by deed Saddam Hussein has pursued his ambition to dominate Iraq and the broader Middle East using the only means he knows, intimidation, coercion and annihilation of all those who might stand in his way. For Saddam Hussein, possession of the world&#39;s most deadly weapons is the ultimate trump card, the one he most hold to fulfill his ambition. <a href="#p295">#</a></p>

<a name="p296"></a><p id="mp296">We know that Saddam Hussein is determined to keep his weapons of mass destruction; he&#39;s determined to make more. Given Saddam Hussein&#39;s history of aggression, given what we know of his grandiose plans, given what we know of his terrorist associations and given his determination to exact revenge on those who oppose him, should we take the risk that he will not some day use these weapons at a time and the place and in the manner of his choosing at a time when the world is in a much weaker position to respond? <a href="#p296">#</a></p>
<a name="p297"></a><p id="mp297">The United States will not and cannot run that risk to the American people. Leaving Saddam Hussein in possession of weapons of mass destruction for a few more months or years is not an option, not in a post-September 11th world. <a href="#p297">#</a></p>
<a name="p298"></a><p id="mp298">My colleagues, over three months ago this council recognized that Iraq continued to pose a threat to international peace and security, and that Iraq had been and remained in material breach of its disarmament obligations. Today Iraq still poses a threat and Iraq still remains in material breach. <a href="#p298">#</a></p>
<a name="p299"></a><p id="mp299">Indeed, by its failure to seize on its one last opportunity to come clean and disarm, Iraq has put itself in deeper material breach and closer to the day when it will face serious consequences for its continued defiance of this council. <a href="#p299">#</a></p>
<a name="p300"></a><p id="mp300">My colleagues, we have an obligation to our citizens, we have an obligation to this body to see that our resolutions are complied with. We wrote 1441 not in order to go to war, we wrote 1441 to try to preserve the peace. We wrote 1441 to give Iraq one last chance. Iraq is not so far taking that one last chance. <a href="#p300">#</a></p>
<a name="p301"></a><p id="mp301">We must not shrink from whatever is ahead of us. We must not fail in our duty and our responsibility to the citizens of the countries that are represented by this body. <a href="#p301">#</a></p>

<a name="p302"></a><p id="mp302">Thank you, Mr. President <a href="#p302">#</a></p></div>
