---
title: "Open Source, Product Design, and DiSo"
layout: post
tp_urlid: "6a010534988cd3970b0120a5b36c0c970c"
tp_favoritecount: 0
tp_commentcount: 1
tp_permalink: "http://www.monkinetic.com/2008/01/open-source-product-design-and-diso.html"
---
This started out as a post to the [diso mailing list](http://groups.google.com/group/diso), but drifted. ;-)

## Open Source, Product Design, and DiSo

*Wherein Steve looks at two small reasons why Facebook "works" and what that means for [the inside-out social network](http://diso-project.org).*

I wanted to put out some thoughts this morning about an aspect of DiSo that we haven't touched on a lot. This is, in some ways, a response to Chris's most recent post, [The problem with open source design](http://factoryjoe.com/blog/2008/01/03/the-problem-with-open-source-design/). But this isn't really about design per se.

Of course, it was 3 am and I was up to get a drink, and decided to check Google Reader... I saw Chris's post and was awake for another 40 minutes thinking about it - open source, DiSo, and product design.

## Facebook and the "Big Lebowski" Effect

My wife just signed up on Facebook because she got an invite from a friend. It happened to be up on the screen when I went to check Reader, and I had to admit, once again, that Facebook really "hangs together" well. One reason Facebook works is because (as the silo that some of us are eager to get out of) there is a real focus internally on visual and funtional consistency, on design. Unlike MySpace, Facebook does not allow for personalized home/profile pages, so users know what to expect on most any profile page - an attractive interface with common components in .

I call it the "Big Lebowski" effect ("That rug really tied the room together."). DiSo is facing a fundemental challenge here: as a decentralized system, how do we provide the sense that it is "tied together" by something? This is important to real users and should be important to us.

Chris has a tip:

>Be clear about the problem youre solving. Nothing spells disaster for a design process more than fishtailing. If you dont know what problems youre trying to solve and you dont have razor-sharp focus on it, chances are youll be open to whatever feedback you can get your hands on, grasping for some notion of what the hell you should be working on.

## Facebook and the Shared Experience

That "tied together" feeling also creates in Facebook a shared experience between its users that adds to the sense of comfort and community. Members use a common interface and share applications, a flood of news updates, application messages, and "pokes". It can get overwhelming, and requires constant "care" to keep up. But everyone is doing it, and the churn is another shared experience that keeps members coming back.

Ideally, DiSo will give users more control over their social interactions, but as we work to solve the thorny "distributed" issues, let's not forget the "social" ones. My wife has [her own Wordpress blog](http://speakshermind.redmonk.net) and thinks DiSo is a great idea - but to be really useful to her it has to maintain that fun, social quality while adopting the distributed/self-determined model.

## Recommendations for moving DiSo forward

Ok, I'm on thin ice in the practical "what to do about it" section, but here are some ideas (in no particluar order). I'd love to get feedback, and we'll be discussing this on the list as well.

* DiSo needs some visual/process design: Some facets will be influenced by the host platform (i.e. Wordpress) but others should be consistent across platforms so that uses begin to be able to identify DiSo-powered sites by more than a 80x60 pixel badge. ;-)
* A common profile page: subject to some theme-matching CSS, there should be a common profile page generated by DiSo. "My DiSo Profile" should be hosted on the user's blog but should be recognizable to any DiSo user as what it is - representative of the author's connection to the DiSo network.
* Some branding: I don't want to create another club - quite the opposite in fact. But there is value in being able to clearly communicate what you're on about and branding gives you a hook to hang that on.
* We need to work on groups in the DiSo-verse. Chris and I have been brainstorming on this and hopefully one of both of us will have some time to write up our thoughts on it soon. Being able to say "I'm a part of such-and-such group" is a powerful statement of self-ideation, and it's one that I for one want in DiSo.

Thanks for reading - if this stuff is interesting to you, come join us on the [mailing list](http://groups.google.com/group/diso) and participate!
